<p style="text-align: center; font-size: 35px">به نام خدا</p>
<p style="text-align: center; font-size: 25px">هوش مصنوعی</p>
<p style="text-align: center; font-size: 25px">تمرین کامپیوتری شماره 3</p>
<p style="text-align: center; font-size: 25px">علی مهرانی</p>
<p style="text-align: center; font-size: 25px">شماره دانشجویی : 810198542</p>

In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import pandas
import time
from sklearn.model_selection import train_test_split
import cv2
TESTSPLITRATIO = 0.3

# Phase 1 - Data analysis

In [3]:
pkl_data_file = open('dataset/data.pkl', 'rb')
data = pickle.load(pkl_data_file)
print(len(data))

pkl_label_file = open('dataset/label.pkl', 'rb')
label = pickle.load(pkl_label_file)
print(len(label))

6000
6000


## train-test split

### q1
In this section we use sklearn library to split data to train and test.   
the split ratio is considered 0.3.   
according to many sources a good ratio to split train-test data should be 0.8/0.2 or 0.7/0.3 or values close.      

In [61]:
label_train, label_test, data_train, data_test = train_test_split(label, data, test_size=TESTSPLITRATIO)

### q2

### q3
In this section we use cv2 package to resize image.  
Then we change all non-0 values to 1 in the newly resized picture.   
The reason we resize pictures is that we can check and compare pixel values with train data directly in naive bayes without having to check image size and scaling.     

In [62]:
data_train_resized = []
data_test_resized = []

for i in data_train :
    row = cv2.resize(i, (20,20))
    row[row>0]=1 #comment this line to avoid changing non-0 valus to 1
    data_train_resized.append(row)
    
for i in data_test :
    row = cv2.resize(i, (20,20))
    row[row>0]=1 #comment this line to avoid changing non-0 valus to 1
    data_test_resized.append(row)

print(label_train[150])
print(data_train_resized[150])
print(label_test[150])
print(data_test_resized[150])

9
[[0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]]
4
[[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 

### q4